
name: Build releases

# Controls when the action will run. 
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
      
  pull_request:
    branches:
      - '**'
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      #Build new binary using old binary and moves scripts
      - name: Build
        run: |
          export BINARY=$(find ./build -type f -name 'gBuild*.jar')
          java -jar "$BINARY" -v build

